#!/bin/bash
. ./lib

options=()
options+=("gimp" "" on)
options+=("inkscape" "" on)
options+=("dia" "" off)
options+=("calligra-krita" "" off)

sel=$(whiptail --backtitle "$apptitle" --title "Graphic applications :" --checklist "Choose what you want" --cancel-button "Back" 0 0 0 \
  "${options[@]}" \
  3>&1 1>&2 2>&3)
if [ ! "$?" = "0" ]; then
  exit 1
fi

for itm in $sel; do
  case $itm in
    #'""') aurpkg="$aurpkg $(echo $itm | sed 's/"//g')";;
    *) pkg="$pkg $(echo $itm | sed 's/"//g')";;
  esac
done

instpkg "$pkg" "$aurpkg"

for itm in $sel; do
  case $itm in
    '"gimp"') choosepkg "gimp-help-";;
  esac
done

exit 0
