#!/bin/bash
. ./lib

options=()
options+=("alsa-utils" "Sound support" on)
options+=("alsa-plugins" "Extra alsa plugins" on)
#options+=("lib32-alsa-plugins" "Extra alsa plugins" on)
options+=("pulseaudio" "Sound server" on)
options+=("pulseaudio-alsa" "ALSA Configuration for PulseAudio" on)

sel=$(whiptail --backtitle "$apptitle" --title "System Sound Install" --checklist "" --cancel-button "Back" 0 0 0 \
  "${options[@]}" \
  3>&1 1>&2 2>&3)
if [ ! "$?" = "0" ]; then
  exit 1
fi

for itm in $sel; do
  case $itm in
    *) pkg="$pkg $(echo $itm | sed 's/"//g')";;
  esac
done

instpkg "$pkg" "$aurpkg"

exit 0
