#!/bin/bash
. ./lib

options=()

items=$(for i in $(pacman -Sqg kde-applications-meta); do echo ${i#kde-meta-};done)
for item in $items; do
  case $item in
    "kdebase") options+=("$item" "" on);;
    "kdeadmin") options+=("$item" "" on);;
    "kdegraphics") options+=("$item" "" on);;
    "kdemultimedia") options+=("$item" "" on);;
    "kdeutils") options+=("$item" "" on);;
    "kdepim") options+=("$item" "" on);;
    "kdeartwork") options+=("$item" "" on);;
    "kde-wallpapers") ;;
    *) options+=("$item" "" off);;
  esac
done

sel=$(whiptail --backtitle "$apptitle" --title "KDE Meta Packages :" --checklist "" --cancel-button "Back" 0 0 0 \
  "${options[@]}" \
  3>&1 1>&2 2>&3)

if [ ! "$?" = "0" ]; then
  exit 1
fi

for itm in $sel; do
  pkg="$pkg $(echo $itm | sed 's/"//g')"
done

instpkg "$pkg" "$aurpkg"

exit 0
