#!/bin/bash
. ./lib

options=()

package=""
items=$(pacman -Sqg $package)
for item in $items; do
  case $item in
    "dolphin" | \
    "kdepasswd" | \
    "kdialog" | \
    "kfind" | \
    "workspace" | \
    "ksystemlog" | \
    "kuser" | \
    "ark" | \
    "kgamma" | \
    "ksnapshot" | \
    "okular" | \
    "audiocd-kio" | \
    "ffmpegthumbs" | \
    "kmix" | \
    "mplayerthumbs" | \
    "filesharing" | \
    "zeroconf-ioslave" | \
    "kate" | \
    "thumbnailers" | \
    "akregator" | \
    "kaddressbook" | \
    "kalarm" | \
    "kleopatra" | \
    "kmail" | \
    "knotes" | \
    "kontact" | \
    "korganizer" | \
    "kdebase-dolphin" | \
    "kdebase-kdepasswd" | \
    "kdebase-kdialog" | \
    "kdebase-kfind" | \
    "kdebase-workspace" | \
    "konsole" | \
    "kwrite" | \
    "kcron" | \
    "kdeadmin-ksystemlog" | \
    "kdeadmin-kuser" | \
    "kdeutils-ark" | \
    "filelight" | \
    "kcalc" | \
    "kcharselect" | \
    "print-manager" | \
    "kdegraphics-kgamma" | \
    "kdegraphics-ksnapshot" | \
    "kdegraphics-okular" | \
    "kdemultimedia-audiocd-kio" | \
    "kdemultimedia-ffmpegthumbs" | \
    "kdemultimedia-kmix" | \
    "kdemultimedia-mplayerthumbs" | \
    "kdenetwork-filesharing" | \
    "kdenetwork-zeroconf-ioslave" | \
    "kate" | \
    "kdesdk-thumbnailers" | \
    "kdepim-akregator" | \
    "kdepim-kaddressbook" | \
    "kdepim-kalarm" | \
    "kdepim-kleopatra" | \
    "kdepim-kmail" | \
    "kdepim-knotes" | \
    "kdepim-kontact" | \
    "kdepim-korganizer" | \
    "kdeartwork-"*) options+=("$item" "" on);;
    *) options+=("$item" "" off);;
  esac
done

sel=$(whiptail --backtitle "$apptitle" --title "$package Install :" --checklist "" --cancel-button "Back" 0 0 0 \
  "${options[@]}" \
  3>&1 1>&2 2>&3)

if [ ! "$?" = "0" ]; then
  exit 1
fi

for itm in $sel; do
  pkg="$pkg $(echo $itm | sed 's/"//g')"
done

instpkg "$pkg" "$aurpkg"

exit 0
