#!/bin/bash
. ./lib

options=()
options+=("/etc/profile.d/alias.sh" "")
options+=("/etc/profile.d/ps1.sh" "")
options+=("Update .bashrc" "")

defaultitem=""
sel=$(whiptail --backtitle "$apptitle" --title "Bash Configuration :" --menu "" --default-item "$defaultitem" --cancel-button "Back" 0 0 0 \
  "${options[@]}" \
  3>&1 1>&2 2>&3)
if [ ! "$?" = "0" ]; then
  exit 1
fi
sed -i "/^defaultitem=/c\defaultitem=\"$sel\"" $0

case $sel in
  '/etc/profile.d/alias.sh') script config/bash/aliases;;
  '/etc/profile.d/ps1.sh') script config/bash/ps1;;
  'Update .bashrc') script config/bash/bashrc;;
esac

exit 0
