#!/bin/bash
. ./lib

options=()
options+=("gksu" "" on)
options+=("gvfs" "" on)
options+=("gvfs-afc" "" on)
options+=("udisks" "" on)
options+=("network-manager-applet" "" on)

sel=$(whiptail --backtitle "$apptitle" --title "XFCE4 Complements :" --checklist "" --cancel-button "Back" 0 0 0 \
  "${options[@]}" \
  3>&1 1>&2 2>&3)
if [ ! "$?" = "0" ]; then
  exit 1
fi

for itm in $sel; do
  case $itm in
    *) pkg="$pkg $(echo $itm | sed 's/"//g')";;
  esac
done

instpkg "$pkg" "$aurpkg"

pressanykey

exit 0
