#!/bin/bash
. ./lib

options=()
options+=("Bash" "")
options+=("Firewall" "")
options+=("Users" "")
options+=("Sudoers" "")
options+=("XOrg" "")
options+=("Grub" "")

defaultitem=""
sel=$(whiptail --backtitle "$apptitle" --title "Config Menu :" --menu "" --default-item "$defaultitem" --cancel-button "Back" 0 0 0 \
  "${options[@]}" \
  3>&1 1>&2 2>&3)
if [ ! "$?" = "0" ]; then
  exit 1
fi
sed -i "/^defaultitem=/c\defaultitem=\"$sel\"" $0

case $sel in
  'Bash') menu config/bash/menu;;
  'Firewall') menu config/firewall/menu;;
  'Users') menu config/users/menu;;
  'Sudoers') menu config/sudoers/menu;;
  'XOrg') menu config/xorg/menu;;
  'Grub') nano /etc/default/grub
          if(confirm "Run grub-mkconfig -o /boot/grub/grub.cfg ?") then
            grub-mkconfig -o /boot/grub/grub.cfg
          fi;;
esac

exit 0
