#!/bin/bash
. ./lib

if ( confirm "MadCatz Mad R.A.T.3 patch for xorg. This correct the stop working mouse bug after start X session.\n\nCreate /usr/share/X11/xorg.conf.d/50-madcatzrat3.conf ?" ) then
cat << EOF > /usr/share/X11/xorg.conf.d/50-madcatzrat3.conf
Section "InputClass"
  Identifier "Madcatz Mad Catz R.A.T.3"
  MatchProduct "Madcatz Mad Catz R.A.T.3 Mouse"
  MatchDevicePath "/dev/input/event*"
  Option "ButtonMapping" "1 2 3 4 5 6 7 8 9 0 0 0 13 14 15 16 17 18"
EndSection
EOF
fi

exit 0
