#!/bin/bash
. ./lib

options=()
#options+=("numlockx" "" on)

sel=$(whiptail --backtitle "$apptitle" --title "XOrg Complements :" --checklist "" --cancel-button "Back" 0 0 0 \
  "${options[@]}" \
  3>&1 1>&2 2>&3)
if [ ! "$?" = "0" ]; then
  exit 1
fi

for itm in $sel; do
  case $itm in
    *) pkg="$pkg $(echo $itm | sed 's/"//g')";;
  esac
done

instpkg "$pkg" "$aurpkg"

for itm in $sel; do
  case $itm in
    '"numlockx"')
      if ( confirm "Add numlockx on to /usr/share/config/kdm/Xsetup ?" ) then
        echo "numlockx on" >> /usr/share/config/kdm/Xsetup
      fi
    ;;
  esac
done

exit 0
