#!/bin/bash
. ./lib

options=()
options+=("os-prober" "Detect OS for multi-boot (grub)" off)
options+=("snapper" "snapshot manager (ext4, lvm, btrfs)" off)
options+=("dosfstools" "FAT32 file support (Windows Drives)" on)
options+=("ntfs-3g" "NTFS file support (Windows Drives)" on)
options+=("btrfs-progs" "BTRFS file utils" on)
options+=("gptfdisk" "" on)
options+=("autofs" "" on)
options+=("fuse" "" on)
options+=("fuseiso" "" on)
options+=("samba" "" off)
options+=("nfs-utils" "" off)
options+=("open-iscsi" "" off)
options+=("sshfs" "" off)
#options+=("mtpfs" "" off)
#options+=("unionfs-fuse" "" off)
#options+=("glusterfs" "" off)
#options+=("fuse-exfat" "" off)
#options+=("exfat-utils" "" off)
#options+=("f2fs-tools" "" off)
#options+=("nilfs-utils" "" off)
#options+=("favfs2" "" off)
#options+=("gnome-vfs" "" off)
#options+=("s3fs-fuse" "" off)
#options+=("hfsprogs" "" off)

sel=$(whiptail --backtitle "$apptitle" --title "File System Install" --checklist "" --cancel-button "Back" 0 0 0 \
  "${options[@]}" \
  3>&1 1>&2 2>&3)

if [ ! "$?" = "0" ]; then
  exit 1
fi

for itm in $sel; do
  case $itm in
    *) pkg="$pkg $(echo $itm | sed 's/"//g')";;
  esac
done

instpkg "$pkg" "$aurpkg"

exit 0
