#!/bin/bash
. ./lib

options=()
#options+=("sddm-kcm" "" off)
options+=("networkmanager" "" on)
options+=("partitionmanager" "" on)
options+=("kmix" "" on)
#plasma-nm
#muon (package manager)
#options+=("kdesu" "" on)
#options+=("kdesu4" "" on)
options+=("gnome-keyring" "" on)
#options+=("konsolepart4" "" on)
#options+=("octopi" "(AUR)" on)
#options+=("kde-gtk-config" "" on)
#options+=("oxygen-gtk2" "" on)
#options+=("oxygen-gtk3-git" "(AUR)" off)
#options+=("breeze-kde4" "" on)
#options+=("breeze" "" on)
#options+=("archlinux-themes-kdm" "" on)
#options+=("numlockx" "" on)
#options+=("kdeconnect" "" off)
#options+=("kdeconnect+sshfs" "" off)

sel=$(whiptail --backtitle "$apptitle" --title "Plasma Complements :" --checklist "" --cancel-button "Back" 0 0 0 \
  "${options[@]}" \
  3>&1 1>&2 2>&3)
if [ ! "$?" = "0" ]; then
  exit 1
fi

for itm in $sel; do
  case $itm in
    '"octopi"') aurpkg="$aurpkg $(echo $itm | sed 's/"//g')";;
    '"oxygen-gtk3-git"') aurpkg="$aurpkg $(echo $itm | sed 's/"//g')";;
    *) pkg="$pkg $(echo $itm | sed 's/"//g')";;
  esac
done

instpkg "$pkg" "$aurpkg"

for itm in $sel; do
  case $itm in
    '"networkmanager"')
      systemctl disable dhcpcd
      if (svcenable NetworkManager) then
        svcdisable dhcpd
      fi
    ;;
    '"numlockx"')
      if ( confirm "Add numlockx on to /usr/share/config/kdm/Xsetup ?" ) then
        echo "numlockx on" >> /usr/share/config/kdm/Xsetup
      fi
    ;;
  esac
done

exit 0
