#!/bin/bash
. ./lib

options=()
options+=("Plasma Packages" "")
#options+=("Plasma Meta Full" "pacman -S plasma-meta")
#options+=("Plasma Full" "pacman -S plasma")
options+=("KDE Apps" "")
options+=("Complements" "")

defaultitem=""
sel=$(whiptail --backtitle "$apptitle" --title "Plasma5 Install Menu :" --menu "" --default-item "$defaultitem" --cancel-button "Back" 0 0 0 \
  "${options[@]}" \
  3>&1 1>&2 2>&3)
if [ ! "$?" = "0" ]; then
  exit 1
fi
sed -i "/^defaultitem=/c\defaultitem=\"$sel\"" $0

case $sel in
  'Plasma Packages') menu install/desktop/plasma5/plasma-packages;;
  'Plasma Meta Full') instpkg "plasma-meta" "";;
  'Plasma Full') instpkg "plasma" "";;
  'KDE Plasma') script install/desktop/plasma5/kdeplasma;;
  'KDE Apps') menu install/desktop/plasma5/kdeapps;;
  'Complements') script install/desktop/plasma5/complements;;
esac

exit 0
