#!/bin/bash
. ./lib

options=()

package=""
options+=("enlightenment" "" on)
options+=("connman" "" on)
options+=("acpid" "" on)

sel=$(whiptail --backtitle "$apptitle" --title "Enlightenment Install :" --checklist "" --cancel-button "Back" 0 0 0 \
  "${options[@]}" \
  3>&1 1>&2 2>&3)
if [ ! "$?" = "0" ]; then
  exit 1
fi

for itm in $sel; do
  pkg="$pkg $(echo $itm | sed 's/"//g')"
done

instpkg "$pkg" "$aurpkg"

exit 0
